/**
 * Text fitting and column arithmetic for the worktree list.
 *
 * Kept apart from `columns.ts` — and free of React and the DOM — because these
 * are the rules that decide whether a row can still be identified when the pane
 * is small, and rules that consequential should be executable in a test rather
 * than only observable in a screenshot.
 */

export const ELLIPSIS = "\u2026";

/**
 * The number of trailing characters worth protecting.
 *
 * Worktree branches here are machine-generated and share long prefixes —
 * `feature-fix-live-activities` against
 * `feature-fix-language-picker-clipping` — so the head is the part every
 * candidate has in common and the tail is the only part that distinguishes
 * them. Trailing truncation therefore deletes precisely the identifying
 * characters and leaves the redundant ones.
 */
export const TAIL_CHARS = 30;

/**
 * The shortest head worth keeping.
 *
 * One or two leading characters of a shared prefix identify nothing and read as
 * a rendering fault — `s…c-fix-language-picker-clipping`. Below this the head is
 * dropped entirely and the space spent on more tail.
 */
const MIN_HEAD = 4;

/**
 * Shorten from the middle, protecting the tail.
 *
 * When there is not even room for the reserved tail the head is dropped
 * entirely rather than split evenly: half a shared prefix plus half a distinct
 * suffix identifies less than a whole distinct suffix.
 */
export function middleTruncate(
  text: string,
  maxChars: number,
  tailChars: number = TAIL_CHARS,
): string {
  const chars = Array.from(text);
  if (maxChars >= chars.length) return text;
  if (maxChars <= 1) return ELLIPSIS;

  let tail = Math.min(tailChars, maxChars - 1);
  let head = maxChars - 1 - tail;
  if (head < MIN_HEAD) {
    head = 0;
    tail = maxChars - 1;
  }

  return (
    chars.slice(0, head).join("") +
    ELLIPSIS +
    chars.slice(chars.length - tail).join("")
  );
}

/**
 * Average advance width of the list's typeface, in pixels per character.
 *
 * A fallback only: `columns.ts` measures the real font where a canvas is
 * available. Deliberately generous, because underestimating makes the JS
 * truncation too long and hands the overflow back to CSS — which trims the
 * tail, the one outcome this whole module exists to prevent.
 */
export const FALLBACK_CHAR_WIDTH = 7.2;

/**
 * How many characters of branch fit in the identifier cell.
 *
 * `repoChars` is what the repository prefix costs on the same line, and is zero
 * in the stacked layout where the repository has a line of its own.
 */
export function branchCharBudget(
  nameWidth: number,
  charWidth: number,
  repoChars: number = 0,
): number {
  const usable = nameWidth - repoChars * charWidth;
  // One character of slack absorbs the difference between the measured average
  // and a name made mostly of wide glyphs.
  return Math.max(4, Math.floor(usable / charWidth) - 1);
}

/** What a repository prefix is allowed to cost before it starts truncating. */
export const MAX_REPO_CHARS = 18;

export function repoCharBudget(name: string): number {
  return Math.min(name.length + 1, MAX_REPO_CHARS + 1);
}

export type ResizableColumn = "status" | "modified" | "size";
export type ColumnWidths = Record<ResizableColumn, number>;

/** The checkbox gutter, which is not resizable and never yields. */
export const CHECKBOX_WIDTH = 14;
export const COLUMN_GAP = 12;

/**
 * The row's own horizontal padding, which the grid tracks lay out inside.
 *
 * Declared here, and applied to the row from here, because it is arithmetic
 * before it is decoration. The pane is measured on the element the rows sit in,
 * so its width is the row's *border* box; the tracks get the content box, which
 * is this much narrower on each side. Leaving the padding as a class on the row
 * and the sum as a number in this file is exactly how the last column came to
 * be sheared off by the clip edge — a value that still read as a plausible one,
 * on the column that says how much space deleting would return.
 */
export const ROW_PADDING_X = 8;

/**
 * Room for a cell's own text, in pixels.
 *
 * The character width is an average, so a string of wide glyphs measures over
 * it; a character of slack covers that. Rounding up rather than down for the
 * same reason — under-reserving here is what puts a value against the clip
 * edge, and half a number is worse than no number.
 */
export function textWidth(sample: string, charWidth: number): number {
  return Math.ceil((sample.length + 1) * charWidth);
}

/**
 * The widest string these columns can ever be asked to show.
 *
 * Both are generated by formatters with bounded output, so this is derivable
 * rather than guessed. `humanBytes` steps up a unit at 1024 and drops the
 * decimal past 100, so `1023 MB` is its longest form below the terabyte tier;
 * the extra digit covers a worktree past 1023 TB, which is not a thing but
 * costs one character to be right about. `relativeTime` tops out at a
 * two-digit count and a two-letter unit.
 */
export const WIDEST_SIZE = "10230 MB";
export const WIDEST_MODIFIED = "99mo";

/** What a sized column must be given if its content is never to be cut. */
export function contentFloor(
  column: "modified" | "size",
  charWidth: number,
): number {
  const sample = column === "size" ? WIDEST_SIZE : WIDEST_MODIFIED;
  return Math.max(MIN_WIDTH[column], textWidth(sample, charWidth));
}

/**
 * The narrowest a column may be made, by any route.
 *
 * Status is bounded by its badge, which is a fixed element rather than text;
 * the other two are bounded by the longest thing their formatter can produce.
 */
export function columnFloor(
  column: ResizableColumn,
  charWidth: number = FALLBACK_CHAR_WIDTH,
): number {
  return column === "status"
    ? MIN_WIDTH.status
    : contentFloor(column, charWidth);
}

/**
 * The identifier's floor.
 *
 * At 240px a stacked row shows about thirty characters of branch, which is
 * enough for the distinguishing tail of every name in a worktree-per-task
 * repository. Nothing may push it below this except a pane that physically
 * cannot hold it.
 */
export const NAME_TARGET = 240;

/**
 * The point past which the identifier stops being an identifier.
 *
 * Below the target the list is already degraded; below this it is useless, so
 * the sized columns are given up entirely before the name is taken this far.
 */
export const NAME_FLOOR = 132;

/** Below this the repository moves onto its own line under the branch. */
export const STACK_BELOW_NAME = 300;

export const DEFAULT_WIDTHS: ColumnWidths = {
  // Badge plus roughly four risk tokens. The column no longer carries prose, so
  // it no longer needs a prose column's width.
  status: 176,
  modified: 60,
  size: 72,
};

/** Below these a column stops being able to show anything useful. */
export const MIN_WIDTH: ColumnWidths = {
  // The verdict badge is 74px and never shrinks; the remainder is one token.
  status: 104,
  modified: 44,
  size: 56,
};

export interface ColumnLayout extends ColumnWidths {
  name: number;
  /** False until the pane has been measured; the grid stays elastic until then. */
  measured: boolean;
  /** The repository renders under the branch rather than before it. */
  stacked: boolean;
  /** Modified is dropped: at this width it costs more than it reports. */
  showModified: boolean;
  /**
   * The pane cannot honour the stored widths, so what is on screen is a forced
   * approximation of them rather than the user's choice.
   */
  compressed: boolean;
  /**
   * Not even the floors fit, so every column has been scaled down and Size can
   * no longer promise to show its value whole.
   *
   * Below the smallest window the app allows, and kept only so that a pane this
   * size still cannot make the list scroll sideways. Anything reasoning about
   * what a column can display should treat this as "no guarantees".
   */
  degenerate: boolean;
}

function yieldFrom(
  current: number,
  floor: number,
  deficit: number,
): [next: number, remaining: number] {
  if (deficit <= 0) return [current, 0];
  const given = Math.min(deficit, Math.max(0, current - floor));
  return [current - given, deficit - given];
}

/**
 * Turn the stored preferences into tracks that fit the pane.
 *
 * The stored widths are preferences, not contracts. Treating them as contracts
 * is what let a 320px Status saved on an external monitor collapse the branch
 * to an unreadable stub on a laptop with the inspector open — the one column
 * carrying the answer paying for the columns carrying the trivia.
 *
 * So surplus goes to the identifier and deficit is taken from everything else
 * first, in ascending order of how much it tells you: Status (tokens, which
 * have slack), then Modified, then Size, then Modified entirely, and only then
 * the name. The result always fits, so the list never scrolls sideways — at the
 * moment of deciding what to delete, scrolling to read a row is worse than any
 * truncation.
 */
export function fitColumns(
  available: number,
  stored: ColumnWidths,
  charWidth: number = FALLBACK_CHAR_WIDTH,
): ColumnLayout {
  if (!Number.isFinite(available) || available <= 0) {
    return {
      ...stored,
      name: NAME_TARGET,
      measured: false,
      stacked: false,
      showModified: true,
      compressed: false,
      degenerate: false,
    };
  }

  const gaps = COLUMN_GAP * 4;
  let budget = available - ROW_PADDING_X * 2 - CHECKBOX_WIDTH - gaps;

  // Modified and Size are told what to say by formatters with bounded output,
  // so "never truncate" is a width that can be reserved rather than hoped for.
  const modifiedFloor = contentFloor("modified", charWidth);
  const sizeFloor = contentFloor("size", charWidth);

  let status = stored.status;
  let modified = Math.max(stored.modified, modifiedFloor);
  let size = Math.max(stored.size, sizeFloor);
  let showModified = true;

  let deficit = NAME_TARGET + status + modified + size - budget;
  if (deficit <= 0) {
    const name = budget - status - modified - size;
    return {
      name,
      status,
      modified,
      size,
      measured: true,
      stacked: name < STACK_BELOW_NAME,
      showModified: true,
      compressed: false,
      degenerate: false,
    };
  }

  [status, deficit] = yieldFrom(status, MIN_WIDTH.status, deficit);
  // Down to their content, not to their minimum: a Size column narrower than
  // the number it holds is the column lying, which is worse than it being wide.
  [modified, deficit] = yieldFrom(modified, modifiedFloor, deficit);
  [size, deficit] = yieldFrom(size, sizeFloor, deficit);

  if (deficit > 0) {
    // Dropping the column frees its track and the gap beside it; only the gap
    // adds to the budget, since the track was a consumer of it.
    deficit -= modified + COLUMN_GAP;
    budget += COLUMN_GAP;
    modified = 0;
    showModified = false;
  }

  const wanted = Math.max(
    0,
    deficit > 0
      ? Math.max(NAME_FLOOR, NAME_TARGET - deficit)
      : NAME_TARGET - deficit,
  );
  let name = Math.min(wanted, Math.max(0, budget - status - modified - size));

  // Last resort, and unreachable at any window the app can actually be sized
  // to. A pane too small even for the floors still must not overflow: a list
  // that scrolls sideways at the moment of choosing what to delete is worse
  // than a list that is merely cramped.
  const sum = name + status + modified + size;
  let degenerate = false;
  if (sum > budget) {
    const scale = Math.max(0, budget) / sum;
    name = Math.floor(name * scale);
    status = Math.floor(status * scale);
    modified = Math.floor(modified * scale);
    size = Math.floor(size * scale);
    degenerate = true;
  }

  return {
    name,
    status,
    modified,
    size,
    measured: true,
    stacked: name < STACK_BELOW_NAME,
    showModified,
    compressed: true,
    degenerate,
  };
}

/**
 * The grid both the header and every row lay themselves out from.
 *
 * One template shared rather than matching Tailwind width classes in two files:
 * that is what makes the columns actually line up, and the previous version
 * drifted the moment a column changed on one side only.
 */
export function gridTemplate(layout: ColumnLayout): string {
  if (!layout.measured) {
    // Before the first measurement, CSS does the same job less precisely: a
    // real minimum on the name and preferred maxima elsewhere.
    return [
      `${CHECKBOX_WIDTH}px`,
      `minmax(min(${NAME_TARGET}px, 30%), 1fr)`,
      `minmax(0, ${layout.status}px)`,
      `minmax(0, ${layout.modified}px)`,
      `minmax(0, ${layout.size}px)`,
    ].join(" ");
  }

  const tracks = [
    `${CHECKBOX_WIDTH}px`,
    `${layout.name}px`,
    `${layout.status}px`,
  ];
  if (layout.showModified) tracks.push(`${layout.modified}px`);
  tracks.push(`${layout.size}px`);
  return tracks.join(" ");
}

/**
 * The room a drag has to move a boundary, in pixels.
 *
 * Resizing stays available — it was asked for — but it cannot be allowed to
 * push the identifier under its target, and it cannot run at all while the pane
 * is already compressing the stored widths, because the number it would save
 * describes a pane the user is not going to stay in.
 */
export interface ResizeRange {
  minDelta: number;
  maxDelta: number;
}

export function resizeRange(
  layout: ColumnLayout,
  stored: ColumnWidths,
  right: ResizableColumn,
  left?: ResizableColumn,
  charWidth: number = FALLBACK_CHAR_WIDTH,
): ResizeRange | null {
  if (layout.compressed) return null;

  const maxDelta = stored[right] - columnFloor(right, charWidth);
  if (left) {
    return { minDelta: columnFloor(left, charWidth) - stored[left], maxDelta };
  }
  // No column to the left: the elastic identifier pays, down to its target.
  return { minDelta: Math.min(0, NAME_TARGET - layout.name), maxDelta };
}

export function applyResize(
  stored: ColumnWidths,
  range: ResizeRange,
  right: ResizableColumn,
  left: ResizableColumn | undefined,
  requestedDelta: number,
): ColumnWidths {
  const delta = Math.min(range.maxDelta, Math.max(range.minDelta, requestedDelta));
  const next: ColumnWidths = { ...stored, [right]: stored[right] - delta };
  if (left) next[left] = stored[left] + delta;
  return next;
}

export function clampWidths(
  widths: ColumnWidths,
  charWidth: number = FALLBACK_CHAR_WIDTH,
): ColumnWidths {
  return {
    status: Math.max(columnFloor("status", charWidth), widths.status),
    modified: Math.max(columnFloor("modified", charWidth), widths.modified),
    size: Math.max(columnFloor("size", charWidth), widths.size),
  };
}

/**
 * The detail panel's width, and what the window will actually allow.
 *
 * `DEFAULT_PANEL_WIDTH` is what it opens at, `MIN_PANEL_WIDTH` what it may
 * never go under, and `MAX_PANEL_FRACTION` how much of the window it may take
 * before the list it is describing stops being a list.
 */
export const DEFAULT_PANEL_WIDTH = 384;
export const MIN_PANEL_WIDTH = 300;

/** Leaves enough of the list visible that the panel cannot swallow the window. */
export const MAX_PANEL_FRACTION = 0.6;

/**
 * Fit a panel width to the window it is about to be drawn in.
 *
 * Dragging already respected the maximum; restoring did not, and neither did
 * making the window smaller afterwards. So a 900px panel saved on an external
 * monitor came back on a laptop as a panel wider than the list, with the rows
 * it exists to explain squeezed to nothing — and no way to see that the number
 * came from a window that is not there any more.
 *
 * The floor wins over the ceiling when the two cross. Below about 500px of
 * window the fraction is narrower than the minimum, and a panel under its
 * minimum is one whose own contents collide; the window is already past what
 * the app supports at that point, and a too-wide panel is the better failure.
 */
export function clampPanelWidth(width: number, viewportWidth: number): number {
  const wanted = Number.isFinite(width) ? width : DEFAULT_PANEL_WIDTH;
  const ceiling = Number.isFinite(viewportWidth)
    ? Math.round(viewportWidth * MAX_PANEL_FRACTION)
    : Infinity;
  return Math.max(MIN_PANEL_WIDTH, Math.min(wanted, ceiling));
}
